version: '3.8'

services:
  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - "8055:8055"
    environment:
      KEY: ${DIRECTUS_KEY:-123456789}
      SECRET: ${DIRECTUS_SECRET:-your-secret-key}

      DB_CLIENT: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD:-directus}

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD:-password}

      # Settings for Directus
      CORS_ENABLED: 'true'
      CORS_ORIGIN: '*'
      CORS_ALLOW_CREDENTIALS: 'true'

      # Рекомендуемые переменные для работы
      CACHE_ENABLED: 'false'

    depends_on:
      - postgres
    volumes:
      - ./uploads:/directus/uploads
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: directus_postgres
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: ${DIRECTUS_DB_PASSWORD:-directus}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
